/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpContext, HttpResponse } from '@angular/common/http';
import { Service } from '@angular/core';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import { getAuthSession, type GetAuthSession$Params } from '../fn/auth/get-auth-session';
import { listAuthSessions, type ListAuthSessions$Params } from '../fn/auth/list-auth-sessions';
import { revokeAuthSession, type RevokeAuthSession$Params } from '../fn/auth/revoke-auth-session';
import { signIn, type SignIn$Params } from '../fn/auth/sign-in';
import { signOut, type SignOut$Params } from '../fn/auth/sign-out';

import type { AuthSession } from '../models/auth-session';
import type { AuthSessionList } from '../models/auth-session-list';

@Service()
export class AuthService extends BaseService {
  /** Identity and session of the caller (GET /api/auth/session) */
  getAuthSession$Response(
    params?: GetAuthSession$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<AuthSession>> {
    return getAuthSession(this.http, this.rootUrl, params as GetAuthSession$Params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<AuthSession>),
    );
  }

  /** Identity and session of the caller (GET /api/auth/session) */
  getAuthSession(params?: GetAuthSession$Params, context?: HttpContext): Observable<AuthSession> {
    return this.getAuthSession$Response(params as GetAuthSession$Params, context).pipe(
      map((r) => r.body),
    );
  }

  /** Active sessions of the caller (GET /api/auth/sessions) */
  listAuthSessions$Response(
    params?: ListAuthSessions$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<AuthSessionList>> {
    return listAuthSessions(
      this.http,
      this.rootUrl,
      params as ListAuthSessions$Params,
      context,
    ).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<AuthSessionList>),
    );
  }

  /** Active sessions of the caller (GET /api/auth/sessions) */
  listAuthSessions(
    params?: ListAuthSessions$Params,
    context?: HttpContext,
  ): Observable<AuthSessionList> {
    return this.listAuthSessions$Response(params as ListAuthSessions$Params, context).pipe(
      map((r) => r.body),
    );
  }

  /** End one active session of the caller (DELETE /api/auth/sessions/{sessionId}) */
  revokeAuthSession$Response(
    params: RevokeAuthSession$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<unknown>> {
    return revokeAuthSession(
      this.http,
      this.rootUrl,
      params as RevokeAuthSession$Params,
      context,
    ).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<unknown>),
    );
  }

  /** End one active session of the caller (DELETE /api/auth/sessions/{sessionId}) */
  revokeAuthSession(params: RevokeAuthSession$Params, context?: HttpContext): Observable<unknown> {
    return this.revokeAuthSession$Response(params as RevokeAuthSession$Params, context).pipe(
      map((r) => r.body),
    );
  }

  /** Sign in with email and password (POST /api/auth/session) */
  signIn$Response(
    params: SignIn$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<AuthSession>> {
    return signIn(this.http, this.rootUrl, params as SignIn$Params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<AuthSession>),
    );
  }

  /** Sign in with email and password (POST /api/auth/session) */
  signIn(params: SignIn$Params, context?: HttpContext): Observable<AuthSession> {
    return this.signIn$Response(params as SignIn$Params, context).pipe(map((r) => r.body));
  }

  /** End the session of the caller (DELETE /api/auth/session) */
  signOut$Response(
    params: SignOut$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<unknown>> {
    return signOut(this.http, this.rootUrl, params as SignOut$Params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<unknown>),
    );
  }

  /** End the session of the caller (DELETE /api/auth/session) */
  signOut(params: SignOut$Params, context?: HttpContext): Observable<unknown> {
    return this.signOut$Response(params as SignOut$Params, context).pipe(map((r) => r.body));
  }
}
