/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpContext, HttpResponse } from '@angular/common/http';
import { Service } from '@angular/core';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import { getHealthLive, type GetHealthLive$Params } from '../fn/health/get-health-live';
import { getHealthReady, type GetHealthReady$Params } from '../fn/health/get-health-ready';

import type { HealthLive } from '../models/health-live';
import type { HealthReady } from '../models/health-ready';

@Service()
export class HealthService extends BaseService {
  /** Backend process liveness (GET /health/live) */
  getHealthLive$Response(
    params?: GetHealthLive$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<HealthLive>> {
    return getHealthLive(this.http, this.rootUrl, params as GetHealthLive$Params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<HealthLive>),
    );
  }

  /** Backend process liveness (GET /health/live) */
  getHealthLive(params?: GetHealthLive$Params, context?: HttpContext): Observable<HealthLive> {
    return this.getHealthLive$Response(params as GetHealthLive$Params, context).pipe(
      map((r) => r.body),
    );
  }

  /** Backend database readiness (GET /health/ready) */
  getHealthReady$Response(
    params?: GetHealthReady$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<HealthReady>> {
    return getHealthReady(this.http, this.rootUrl, params as GetHealthReady$Params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<HealthReady>),
    );
  }

  /** Backend database readiness (GET /health/ready) */
  getHealthReady(params?: GetHealthReady$Params, context?: HttpContext): Observable<HealthReady> {
    return this.getHealthReady$Response(params as GetHealthReady$Params, context).pipe(
      map((r) => r.body),
    );
  }
}
