/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';
import type { ReadinessAvailable } from '../../models/readiness-available';

export type GetDevelopmentReadiness$Params = Record<string, never>;

export function getDevelopmentReadiness(
  http: HttpClient,
  rootUrl: string,
  _params?: Record<string, never>,
  context?: HttpContext,
): Observable<StrictHttpResponse<ReadinessAvailable>> {
  const rb = new RequestBuilder(rootUrl, getDevelopmentReadiness.PATH, 'get');

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
    map((r) => r as StrictHttpResponse<ReadinessAvailable>),
  );
}

getDevelopmentReadiness.PATH = '/api/readiness';
