/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';
import type { AuthSession } from '../../models/auth-session';

export type GetAuthSession$Params = Record<string, never>;

export function getAuthSession(
  http: HttpClient,
  rootUrl: string,
  _params?: Record<string, never>,
  context?: HttpContext,
): Observable<StrictHttpResponse<AuthSession>> {
  const rb = new RequestBuilder(rootUrl, getAuthSession.PATH, 'get');

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
    map((r) => r as StrictHttpResponse<AuthSession>),
  );
}

getAuthSession.PATH = '/api/auth/session';
