/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface RevokeAuthSession$Params {
  sessionId: string;
  'x-csrf-token': string;
}

export function revokeAuthSession(
  http: HttpClient,
  rootUrl: string,
  params: RevokeAuthSession$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<unknown>> {
  const rb = new RequestBuilder(rootUrl, revokeAuthSession.PATH, 'delete');
  if (params) {
    rb.path('sessionId', params.sessionId);
    rb.header('x-csrf-token', params['x-csrf-token']);
  }
  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
    map((r) => r as StrictHttpResponse<unknown>),
  );
}

revokeAuthSession.PATH = '/api/auth/sessions/{sessionId}';
