/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';
import type { AuthSession } from '../../models/auth-session';
import type { SignInRequest } from '../../models/sign-in-request';

export interface SignIn$Params {
  body: SignInRequest;
}

export function signIn(
  http: HttpClient,
  rootUrl: string,
  params: SignIn$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AuthSession>> {
  const rb = new RequestBuilder(rootUrl, signIn.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }
  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
    map((r) => r as StrictHttpResponse<AuthSession>),
  );
}

signIn.PATH = '/api/auth/session';
