/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface SignOut$Params {
  'x-csrf-token': string;
}

export function signOut(
  http: HttpClient,
  rootUrl: string,
  params: SignOut$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<unknown>> {
  const rb = new RequestBuilder(rootUrl, signOut.PATH, 'delete');
  if (params) {
    rb.header('x-csrf-token', params['x-csrf-token']);
  }
  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
    map((r) => r as StrictHttpResponse<unknown>),
  );
}

signOut.PATH = '/api/auth/session';
