/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

export interface AuthError {
  error:
    | 'Invalid request'
    | 'Invalid credentials'
    | 'Unauthorized'
    | 'Forbidden'
    | 'Not found'
    | 'Unsupported media type'
    | 'Too many requests'
    | 'Service unavailable'
    | 'Internal server error';
}
