/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

export interface AuthSession {
  csrfToken: string;
  session: Record<string, unknown>;
  user: Record<string, unknown>;
}
