/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { Service, makeEnvironmentProviders, type EnvironmentProviders } from '@angular/core';

@Service()
export class ApiConfiguration {
  rootUrl: string = '';
}

export function provideApiConfiguration(rootUrl: string): EnvironmentProviders {
  return makeEnvironmentProviders([
    {
      provide: ApiConfiguration,
      useFactory: () => {
        const c = new ApiConfiguration();
        c.rootUrl = rootUrl;
        return c;
      },
    },
  ]);
}
