/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Service, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';

import { ApiConfiguration } from './api-configuration';
import { StrictHttpResponse } from './strict-http-response';

export type ApiFn<P, R> = (
  http: HttpClient,
  rootUrl: string,
  params: P,
  context?: HttpContext,
) => Observable<StrictHttpResponse<R>>;

/**
 * Helper to invoke any tree-shakeable operation function directly.
 */
@Service()
export class FoundationApi {
  private readonly config = inject(ApiConfiguration);
  private readonly http = inject(HttpClient);

  private _rootUrl?: string;

  get rootUrl(): string {
    return this._rootUrl ?? this.config.rootUrl;
  }
  set rootUrl(url: string) {
    this._rootUrl = url;
  }

  /** Invoke an operation function and stream the response body. */
  invoke<P, R>(fn: ApiFn<P, R>, params: P, context?: HttpContext): Observable<R> {
    return this.invoke$Response(fn, params, context).pipe(map((r) => r.body));
  }

  /** Invoke an operation function and stream the full HTTP response. */
  invoke$Response<P, R>(
    fn: ApiFn<P, R>,
    params: P,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<R>> {
    return fn(this.http, this.rootUrl, params, context).pipe(
      filter((r: unknown): r is HttpResponse<unknown> => r instanceof HttpResponse),
      map((r) => r as StrictHttpResponse<R>),
    );
  }
}
