/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpClient } from '@angular/common/http';
import { Service, inject } from '@angular/core';

import { ApiConfiguration } from './api-configuration';

@Service()
export class BaseService {
  protected readonly config = inject(ApiConfiguration);
  protected readonly http = inject(HttpClient);

  private _rootUrl?: string;

  get rootUrl(): string {
    return this._rootUrl ?? this.config.rootUrl;
  }
  set rootUrl(url: string) {
    this._rootUrl = url;
  }
}
