/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpContext, HttpHeaders, HttpParams, HttpRequest } from '@angular/common/http';

export interface BuildOptions {
  accept?: string;
  responseType?: 'json' | 'text' | 'blob' | 'arraybuffer';
  reportUploadProgress?: boolean;
  reportDownloadProgress?: boolean;
  context?: HttpContext;
}

export class RequestBuilder {
  private readonly _pathParams = new Map<string, unknown>();
  private readonly _queryParams = new Map<string, unknown>();
  private readonly _headerParams = new Map<string, unknown>();
  private _body: unknown = undefined;
  private _bodyContentType: string | undefined;

  constructor(
    public readonly rootUrl: string,
    public readonly operationPath: string,
    public readonly method: string,
  ) {}

  path(name: string, value: unknown): void {
    this._pathParams.set(name, value);
  }

  query(name: string, value: unknown): void {
    this._queryParams.set(name, value);
  }

  header(name: string, value: unknown): void {
    this._headerParams.set(name, value);
  }

  body(value: unknown, contentType = 'application/json'): void {
    if (value instanceof Blob) {
      this._bodyContentType = value.type;
    } else if (value instanceof FormData) {
      // FormData sets its own Content-Type (with boundary) — leave it alone.
      this._bodyContentType = undefined;
    } else {
      this._bodyContentType = contentType;
    }
    this._body = value;
  }

  build<T = unknown>(options: BuildOptions = {}): HttpRequest<T> {
    let path = this.operationPath;
    for (const [name, value] of this._pathParams) {
      path = path.replace('{' + name + '}', encodeURIComponent(value == null ? '' : String(value)));
    }

    let params = new HttpParams();
    for (const [name, value] of this._queryParams) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) {
        for (const v of value) {
          if (v !== undefined && v !== null) params = params.append(name, String(v));
        }
      } else {
        params = params.append(name, String(value));
      }
    }

    let headers = new HttpHeaders();
    if (options.accept) headers = headers.set('Accept', options.accept);
    for (const [name, value] of this._headerParams) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) {
        for (const v of value) headers = headers.append(name, String(v));
      } else {
        headers = headers.set(name, String(value));
      }
    }
    if (this._bodyContentType) {
      headers = headers.set('Content-Type', this._bodyContentType);
    }

    return new HttpRequest<T>(this.method.toUpperCase(), this.rootUrl + path, this._body as T, {
      params,
      headers,
      responseType: options.responseType,
      reportUploadProgress: options.reportUploadProgress,
      reportDownloadProgress: options.reportDownloadProgress,
      context: options.context,
    });
  }
}
