/* eslint-disable */
/* Auto-generated by @ojiepermana/angular/sdk. DO NOT EDIT. */

import { HttpResponse } from '@angular/common/http';

export type StrictHttpResponse<T> = HttpResponse<T> & { readonly body: T };
